export const styles = {
  container: {
    maxWidth: "1000px",
    margin: "0 auto",
    padding: "20px",
    fontFamily: "sans-serif",
  },
  header: {
    marginBottom: "30px",
    borderBottom: "1px solid #eee",
    paddingBottom: "20px",
  },
  headerContent: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  authCard: {
    maxWidth: "400px",
    margin: "80px auto",
    padding: "40px",
    border: "1px solid #eee",
    borderRadius: "12px",
    boxShadow: "0 4px 12px rgba(0,0,0,0.1)",
  },
  formCol: { display: "flex", flexDirection: "column", gap: "15px" },
  searchBox: {
    display: "flex",
    justifyContent: "center",
    marginBottom: "30px",
  },
  formColumn: {
    display: "flex",
    flexDirection: "column",
    gap: "10px",
    width: "100%",
    maxWidth: "600px",
  },
  formRow: { display: "flex", gap: "10px", width: "100%" },
  filterRow: { display: "flex", gap: "10px", width: "100%" },
  input: {
    padding: "12px",
    fontSize: "16px",
    borderRadius: "6px",
    border: "1px solid #ddd",
    flex: 1,
  },
  select: {
    padding: "12px",
    fontSize: "16px",
    borderRadius: "6px",
    border: "1px solid #ddd",
    flex: 1,
    backgroundColor: "white",
    cursor: "pointer",
  },
  primaryButton: {
    padding: "12px 20px",
    backgroundColor: "#6366f1",
    color: "white",
    border: "none",
    borderRadius: "6px",
    cursor: "pointer",
    fontWeight: "bold",
  },
  secondaryButton: {
    padding: "12px 20px",
    backgroundColor: "#10b981",
    color: "white",
    border: "none",
    borderRadius: "6px",
    cursor: "pointer",
    fontWeight: "bold",
  },
  navButton: {
    padding: "8px 16px",
    backgroundColor: "#333",
    color: "white",
    border: "none",
    borderRadius: "4px",
    cursor: "pointer",
  },
  navButtonOutline: {
    padding: "8px 16px",
    backgroundColor: "white",
    color: "#333",
    border: "1px solid #333",
    borderRadius: "4px",
    cursor: "pointer",
  },
  logoutButton: {
    padding: "8px 16px",
    backgroundColor: "#e5e7eb",
    color: "#333",
    border: "none",
    borderRadius: "4px",
    cursor: "pointer",
  },
  backButton: {
    marginBottom: "20px",
    padding: "8px 16px",
    backgroundColor: "#f0f0f0",
    border: "none",
    borderRadius: "4px",
    cursor: "pointer",
  },
  linkText: {
    marginTop: "20px",
    textAlign: "center",
    fontSize: "14px",
    color: "#666",
  },
  authSection: { display: "flex", alignItems: "center", gap: "10px" },
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(200px, 1fr))",
    gap: "20px",
  },
  card: {
    border: "1px solid #eee",
    borderRadius: "12px",
    overflow: "hidden",
    height: "100%",
    cursor: "pointer",
    transition: "transform 0.2s",
    "&:hover": { transform: "translateY(-5px)" },
  },
  image: { width: "100%", height: "280px", objectFit: "cover" },
  content: { padding: "12px" },
  centerText: {
    textAlign: "center",
    marginTop: "50px",
    fontSize: "1.2rem",
    color: "#666",
  },
  paginationWrapper: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "15px",
    marginTop: "40px",
    paddingBottom: "20px",
  },
  paginationBtnRow: {
    display: "flex",
    gap: "5px",
    flexWrap: "wrap",
    justifyContent: "center",
  },
  squareBtn: {
    minWidth: "32px",
    height: "32px",
    padding: "0 6px",
    backgroundColor: "white",
    border: "1px solid #ddd",
    borderRadius: "4px",
    color: "#333",
    cursor: "pointer",
    fontSize: "13px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  activeSquareBtn: {
    minWidth: "32px",
    height: "32px",
    padding: "0 6px",
    backgroundColor: "white",
    border: "1px solid #f97316",
    borderRadius: "4px",
    color: "#f97316",
    fontWeight: "bold",
    cursor: "pointer",
    fontSize: "13px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  pageFormInput: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    backgroundColor: "#f9f9f9",
    padding: "8px 16px",
    borderRadius: "20px",
  },
  pageInput: {
    width: "50px",
    padding: "6px",
    textAlign: "center",
    borderRadius: "4px",
    border: "1px solid #ccc",
  },
  pageInfo: { fontSize: "14px", color: "#555" },
  goButton: {
    padding: "6px 12px",
    backgroundColor: "#333",
    color: "white",
    border: "none",
    borderRadius: "4px",
    cursor: "pointer",
    fontSize: "12px",
  },
  detailCard: {
    backgroundColor: "white",
    borderRadius: "16px",
    padding: "40px",
    boxShadow: "0 10px 30px rgba(0,0,0,0.08)",
    marginBottom: "40px",
  },
  detailHeader: {
    borderBottom: "1px solid #eee",
    paddingBottom: "20px",
    marginBottom: "30px",
  },
  detailBody: { display: "flex", gap: "40px", flexWrap: "wrap" },
  imageWrapper: { flexShrink: 0 },
  detailImage: {
    width: "320px",
    borderRadius: "12px",
    boxShadow: "0 8px 20px rgba(0,0,0,0.2)",
  },
  detailInfo: { flex: 1, minWidth: "300px" },
  tagContainer: {
    display: "flex",
    flexWrap: "wrap",
    gap: "10px",
    marginBottom: "25px",
  },
  badge: {
    backgroundColor: "#f3f4f6",
    padding: "8px 14px",
    borderRadius: "20px",
    fontSize: "14px",
    color: "#374151",
    fontWeight: "600",
    border: "1px solid #e5e7eb",
  },
  synopsis: {
    lineHeight: "1.8",
    color: "#4b5563",
    backgroundColor: "#f9fafb",
    padding: "20px",
    borderRadius: "12px",
    marginBottom: "25px",
    fontSize: "15px",
  },
  linkButton: {
    display: "inline-block",
    backgroundColor: "#2e51a2",
    color: "white",
    padding: "12px 24px",
    borderRadius: "8px",
    textDecoration: "none",
    fontWeight: "bold",
    transition: "background 0.2s",
  },
  videoContainer: { marginTop: "50px" },
  reviewContainer: {
    backgroundColor: "white",
    borderRadius: "16px",
    padding: "30px",
    boxShadow: "0 4px 15px rgba(0,0,0,0.05)",
    marginTop: "20px",
  },
  reviewForm: {
    backgroundColor: "#f9f9f9",
    padding: "20px",
    borderRadius: "12px",
    marginBottom: "30px",
  },
  textarea: {
    width: "100%",
    padding: "12px",
    borderRadius: "6px",
    border: "1px solid #ddd",
    marginTop: "10px",
    fontSize: "14px",
    boxSizing: "border-box",
  },
  reviewButton: {
    marginTop: "10px",
    padding: "10px 20px",
    backgroundColor: "#333",
    color: "white",
    border: "none",
    borderRadius: "6px",
    cursor: "pointer",
    fontWeight: "bold",
  },
  loginMessage: {
    textAlign: "center",
    padding: "30px",
    backgroundColor: "#f3f4f6",
    borderRadius: "12px",
    marginBottom: "30px",
  },
  reviewList: { display: "flex", flexDirection: "column", gap: "15px" },
  reviewItem: { borderBottom: "1px solid #eee", paddingBottom: "15px" },
  reviewHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "8px",
  },
  reviewTitle: { fontWeight: "bold", fontSize: "16px" },
  reviewRating: { color: "#f59e0b", fontWeight: "bold" },
  reviewContent: { color: "#444", lineHeight: "1.5", marginBottom: "8px" },
  reviewFooter: {
    fontSize: "12px",
    color: "#888",
    display: "flex",
    justifyContent: "space-between",
  },
  deleteButton: {
    backgroundColor: "#ef4444",
    color: "white",
    border: "none",
    padding: "5px 10px",
    borderRadius: "4px",
    fontSize: "12px",
    cursor: "pointer",
  },
  myPageSection: {
    marginBottom: "30px",
    padding: "20px",
    border: "1px solid #eee",
    borderRadius: "12px",
    backgroundColor: "#f9f9f9",
  },
  myReviewItem: {
    padding: "15px",
    border: "1px solid #ddd",
    borderRadius: "8px",
    marginBottom: "10px",
    backgroundColor: "white",
  },
  reviewTitleLink: {
    textDecoration: "none",
    color: "#6366f1",
    fontWeight: "bold",
    fontSize: "1.1rem",
    "&:hover": { textDecoration: "underline" },
  },
  myReviewHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "5px",
  },
  myReviewBody: {
    color: "#666",
    marginTop: "5px",
  },
  myReviewFooter: {
    display: "flex",
    justifyContent: "flex-end",
    fontSize: "0.8rem",
    color: "#888",
    marginTop: "10px",
  },
};